### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by tbleckert** [tbleckert/laramill#2]
I feel that a better name would be good, "billing" is too common and maybe something that hints "Paymill". Or just keep it, but worth thinking about.

**Comment by ChristopherDosin** [comment]
BillMill :dancer: 
LaraMill
LaraPay

**Comment by tbleckert** [comment]
Great suggestions! BillMill sounds cool, what do you think @hostianer ?

**Comment by ChristopherDosin** [comment]
@tbleckert BillMill sounds really goo to me :+1:

**Comment by tbleckert** [comment]
BillMill it is!

**Comment by tbleckert** [comment]
Changed my mind and went with LaraMill to include Laravel in the name. Included a special thanks to you in the README @hostianer
