### ISSUE TITLE
Database Table

### ISSUE THREAD

**Issue by ChristopherDosin** [tbleckert/laramill#5]
I have one question:

With Stripe you have to set up a new migration for the users table for the additional fields.

In your docs i dont find anything about a new database table.

How should the table structure be to use your package ?
Do you have maybe an simple example for me ?

**Comment by tbleckert** [comment]
Yeah sorry, I will explain and add it to the docs as soon as possible. At the moment we only save client ID and subscription ID so the only thing you need to add is client_id and subscription_id fields (varchar) to your users table.
